export const roles = {
  ADMIN: "ADMIN",
  MP: "MP",
  MLA: "MLA",
  MANDAL_INCHARGE: "MANDAL_INCHARGE",
  SECTOR_INCHARGE: "SECTOR_INCHARGE",
  BOOTH_COORDINATOR: "BOOTH_COORDINATOR",
  BOOTH_LEVEL_AGENT: "BOOTH_LEVEL_AGENT",
  POLLING_AGENT: "POLLING_AGENT",
};
